# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171120_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/icon/icon.png', max_length=200, upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
